development:
  adapter: postgresql
  database: photo_dev
  username: LM_Dev
  password:
  encoding: unicode
  pool: 3
  timeout: 1000

test:
  adapter: postgresql
  database: photo_test
  username: LM_Dev
  password:
  encoding: unicode
  pool: 3
  timeout: 1000