development:
  adapter: postgresql
  database: photo_dev
  username: postgres
  password: west10port
  encoding: unicode
  pool: 5
  timeout: 1000

test:
  adapter: postgresql
  database: photo_test
  username: postgres
  password: west10port
  encoding: unicode
  pool: 5
  timeout: 1000