development:
  bucket: snappitt-dev
  access_key_id: 17JTTPKPT2F8YWCFVXG2
  secret_access_key: bYnK5X0NnObQI3R35LlHsEOrlu74mp4D7DuYMf5v
test:
  bucket: snappitt-test
  access_key_id: 17JTTPKPT2F8YWCFVXG2
  secret_access_key: bYnK5X0NnObQI3R35LlHsEOrlu74mp4D7DuYMf5v
production:
  bucket: snappitt0
  access_key_id: 17JTTPKPT2F8YWCFVXG2
  secret_access_key: bYnK5X0NnObQI3R35LlHsEOrlu74mp4D7DuYMf5v